run-backend: 
	python3 run.py

# Use the following targets when using local DB only
local-start-mongo-db:
	brew services restart mongodb-community

local-stop-mongo-db:
	brew services stop mongodb-community
